project:
  type: book
book:    
  author: "Akeem Semper"
  date: "01-Apr-2023"
  title: "ML_Intro_Q_source"
  chapters:
    - index.qmd
    - workbooks/001_Setup.ipynb
    - workbooks/002_Describing_One_Variable_sol.ipynb
    - references.qmd

toc: true
number-sections: true
jupyter: python3
execute: 
  enabled: true

format:
  html:
    output-dir: _output
    css: styles.css
    html-math-method: katex
    theme:
      light: flatly
      dark: darkly
    code-copy: true
    execute: 
      enabled: true
    anchor-sections: true
    smooth-scroll: true
  pdf:
    documentclass: scrreport
  epub:
    cover-image: cover.png