project:
  type: book

title: "ML_Intro_Q_source"

book:    
  author: "Akeem Semper"
  date: "01-Apr-2023"
  chapters:
    - index.qmd
    - workbooks/001_Setup.ipynb
    - workbooks/002_Describing_One_Variable_sol.ipynb
    - references.qmd
  format: 
    pdf:
      documentclass: scrreport
      papersize: letter
      execute: 
        enabled: true
    html:
      output-dir: _output
      css: styles.css
      html-math-method: katex
      theme:
        light: flatly
        dark: darkly
      code-copy: true
      execute: 
        enabled: true
      anchor-sections: true
      smooth-scroll: true

toc: true
number-sections: true
jupyter: python3